export const keyword = 'HOABINH';
export const keywordDisplay = 'HÒA BÌNH';
export const keyColumn = 6;
export function normalize(value) {
 return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/gi, 'd').toUpperCase().replace(/[^A-Z]/g, '');
}
export const questions = [
 {answer:'TRÂN CHÂU CẢNG', keyIndex:5, tag:'Thái Bình Dương', clue:'Ngày 7/12/1941, Nhật Bản tấn công căn cứ hải quân nào của Hoa Kỳ ở Hawaii?', hint:'Tên tiếng Việt gồm ba từ. Trong đó, hai từ đầu có nghĩa là ngọc trai.', explanation:'Cuộc tấn công Trân Châu Cảng ngày 7/12/1941 dẫn tới việc Hoa Kỳ tham chiến trong Thế chiến II.', source:'https://www.nps.gov/perl/', sourceName:'Cục Công viên Quốc gia Hoa Kỳ'},
 {answer:'ĐỒNG MINH', keyIndex:1, tag:'Các bên tham chiến', clue:'Anh, Hoa Kỳ và Liên Xô cùng thuộc phe nào chống lại phe Trục trong Thế chiến II?', hint:'Hai từ chỉ những bên liên kết, cùng chiến đấu vì mục tiêu chung.', explanation:'Anh, Hoa Kỳ và Liên Xô là ba cường quốc chủ chốt của phe Đồng minh. Phe này chống lại phe Trục gồm Đức, Ý, Nhật Bản và các nước liên kết.', source:'https://encyclopedia.ushmm.org/content/en/article/axis-powers-in-world-war-ii', sourceName:'Bảo tàng Tưởng niệm nạn diệt chủng Do Thái Hoa Kỳ'},
 {answer:'BA LAN', keyIndex:3, tag:'Chiến tranh bùng nổ', clue:'Ngày 1/9/1939, Đức tấn công quốc gia nào, mở đầu Thế chiến II tại châu Âu?', hint:'Một quốc gia ở châu Âu có thủ đô là Warszawa.', explanation:'Đức xâm lược Ba Lan ngày 1/9/1939. Hai ngày sau, Anh và Pháp tuyên chiến với Đức.', source:'https://encyclopedia.ushmm.org/content/en/timeline-event/holocaust/1939-1941/britain-and-france-declare-war', sourceName:'Bảo tàng Tưởng niệm nạn diệt chủng Do Thái Hoa Kỳ'},
 {answer:'NHẬT BẢN', keyIndex:4, tag:'Chiến tranh kết thúc', clue:'Quốc gia nào ký văn kiện đầu hàng Đồng minh trên chiến hạm Missouri ngày 2/9/1945?', hint:'Quốc gia này còn được gọi là xứ sở mặt trời mọc.', explanation:'Ngày 2/9/1945, Nhật Bản ký văn kiện đầu hàng trên chiến hạm Missouri ở vịnh Tokyo, chính thức kết thúc Thế chiến II.', source:'https://www.archives.gov/college-park/highlights/japanese-surrender', sourceName:'Cơ quan Lưu trữ Quốc gia Hoa Kỳ'},
 {answer:'LIÊN XÔ', keyIndex:1, tag:'Mặt trận phía Đông', clue:'Ngày 22/6/1941, Đức mở chiến dịch Barbarossa để xâm lược quốc gia nào?', hint:'Tên gọi ngắn gồm hai từ; quốc gia này có thủ đô là Moskva.', explanation:'Đức tấn công Liên Xô ngày 22/6/1941 trong chiến dịch Barbarossa, mở một mặt trận rộng lớn ở phía Đông.', source:'https://www.nationalww2museum.org/war/articles/hitlers-declaration-war-united-states', sourceName:'Bảo tàng Quốc gia về Thế chiến II'},
 {answer:'ANH', keyIndex:1, tag:'Châu Âu năm 1939', clue:'Quốc gia nào cùng Pháp tuyên chiến với Đức ngày 3/9/1939? Điền tên gọi ngắn gồm 3 chữ cái.', hint:'Quốc gia có thủ đô là Luân Đôn.', explanation:'Anh và Pháp tuyên chiến với Đức ngày 3/9/1939 sau cuộc xâm lược Ba Lan. Đây là bước mở rộng chiến tranh tại châu Âu.', source:'https://encyclopedia.ushmm.org/content/en/timeline-event/holocaust/1939-1941/britain-and-france-declare-war', sourceName:'Bảo tàng Tưởng niệm nạn diệt chủng Do Thái Hoa Kỳ'},
 {answer:'HIROSHIMA', keyIndex:5, tag:'Những mất mát', clue:'Thành phố nào của Nhật Bản bị Hoa Kỳ ném bom nguyên tử ngày 6/8/1945? Dùng cách viết quốc tế gồm 9 chữ cái.', aliases:['HIROSIMA'], hint:'Tên thành phố bắt đầu bằng H. Đừng nhầm với Nagasaki.', explanation:'Hiroshima bị ném bom nguyên tử ngày 6/8/1945. Nagasaki bị ném bom ba ngày sau. Hai sự kiện để lại những hậu quả nhân đạo đặc biệt nghiêm trọng.', source:'https://www.nps.gov/wwii/learn/historyculture/august-1945.htm', sourceName:'Cục Công viên Quốc gia Hoa Kỳ'}
].map((q,i)=>({...q,id:i,normalized:normalize(q.answer),start:keyColumn-q.keyIndex}));
export const columns = Math.max(...questions.map(q=>q.start+q.normalized.length));
export function newGame(){ return {active:0, drafts:questions.map(()=>''), solved:questions.map(()=>false), hints:questions.map(()=>false)}; }
export function checkAnswer(index,value){ const q=questions[index]; const cleaned=normalize(value); return cleaned===q.normalized || (q.aliases||[]).some(a=>normalize(a)===cleaned); }
export function solve(game,index,value){ if(!checkAnswer(index,value)) return false; game.solved[index]=true; game.drafts[index]=questions[index].answer; return true; }
export function nextUnsolved(game){ for(let step=1;step<=questions.length;step++){const index=(game.active+step)%questions.length;if(!game.solved[index])return index;}return -1; }
export function unlockedKeyword(game){return game.solved.every(Boolean)?questions.map(q=>q.normalized[q.keyIndex]).join(''):null;}
